// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/leads/leads.proto

package go_micro_service_leads

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewLeadRequest struct {
	FirstName            string                     `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string                     `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string                     `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Contact              string                     `protobuf:"bytes,4,opt,name=contact,proto3" json:"contact,omitempty"`
	Source               string                     `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Meta                 []*NewLeadRequest_KeyValue `protobuf:"bytes,6,rep,name=meta,proto3" json:"meta,omitempty"`
	TemplateValues       []*NewLeadRequest_KeyValue `protobuf:"bytes,7,rep,name=templateValues,proto3" json:"templateValues,omitempty"`
	CampaignTag          string                     `protobuf:"bytes,8,opt,name=campaignTag,proto3" json:"campaignTag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *NewLeadRequest) Reset()         { *m = NewLeadRequest{} }
func (m *NewLeadRequest) String() string { return proto.CompactTextString(m) }
func (*NewLeadRequest) ProtoMessage()    {}
func (*NewLeadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4047e0a29e423ed0, []int{0}
}

func (m *NewLeadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewLeadRequest.Unmarshal(m, b)
}
func (m *NewLeadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewLeadRequest.Marshal(b, m, deterministic)
}
func (m *NewLeadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewLeadRequest.Merge(m, src)
}
func (m *NewLeadRequest) XXX_Size() int {
	return xxx_messageInfo_NewLeadRequest.Size(m)
}
func (m *NewLeadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewLeadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewLeadRequest proto.InternalMessageInfo

func (m *NewLeadRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *NewLeadRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *NewLeadRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NewLeadRequest) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *NewLeadRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *NewLeadRequest) GetMeta() []*NewLeadRequest_KeyValue {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *NewLeadRequest) GetTemplateValues() []*NewLeadRequest_KeyValue {
	if m != nil {
		return m.TemplateValues
	}
	return nil
}

func (m *NewLeadRequest) GetCampaignTag() string {
	if m != nil {
		return m.CampaignTag
	}
	return ""
}

type NewLeadRequest_KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewLeadRequest_KeyValue) Reset()         { *m = NewLeadRequest_KeyValue{} }
func (m *NewLeadRequest_KeyValue) String() string { return proto.CompactTextString(m) }
func (*NewLeadRequest_KeyValue) ProtoMessage()    {}
func (*NewLeadRequest_KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_4047e0a29e423ed0, []int{0, 0}
}

func (m *NewLeadRequest_KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewLeadRequest_KeyValue.Unmarshal(m, b)
}
func (m *NewLeadRequest_KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewLeadRequest_KeyValue.Marshal(b, m, deterministic)
}
func (m *NewLeadRequest_KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewLeadRequest_KeyValue.Merge(m, src)
}
func (m *NewLeadRequest_KeyValue) XXX_Size() int {
	return xxx_messageInfo_NewLeadRequest_KeyValue.Size(m)
}
func (m *NewLeadRequest_KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_NewLeadRequest_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_NewLeadRequest_KeyValue proto.InternalMessageInfo

func (m *NewLeadRequest_KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *NewLeadRequest_KeyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type NewLeadResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewLeadResponse) Reset()         { *m = NewLeadResponse{} }
func (m *NewLeadResponse) String() string { return proto.CompactTextString(m) }
func (*NewLeadResponse) ProtoMessage()    {}
func (*NewLeadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4047e0a29e423ed0, []int{1}
}

func (m *NewLeadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewLeadResponse.Unmarshal(m, b)
}
func (m *NewLeadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewLeadResponse.Marshal(b, m, deterministic)
}
func (m *NewLeadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewLeadResponse.Merge(m, src)
}
func (m *NewLeadResponse) XXX_Size() int {
	return xxx_messageInfo_NewLeadResponse.Size(m)
}
func (m *NewLeadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewLeadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewLeadResponse proto.InternalMessageInfo

func (m *NewLeadResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *NewLeadResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*NewLeadRequest)(nil), "go.micro.service.leads.NewLeadRequest")
	proto.RegisterType((*NewLeadRequest_KeyValue)(nil), "go.micro.service.leads.NewLeadRequest.KeyValue")
	proto.RegisterType((*NewLeadResponse)(nil), "go.micro.service.leads.NewLeadResponse")
}

func init() {
	proto.RegisterFile("proto/leads/leads.proto", fileDescriptor_4047e0a29e423ed0)
}

var fileDescriptor_4047e0a29e423ed0 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xcd, 0x4e, 0xf3, 0x30,
	0x10, 0xfc, 0xfa, 0xa5, 0x3f, 0xe9, 0x56, 0x2a, 0xc8, 0x42, 0xc5, 0xaa, 0x38, 0x54, 0x3d, 0x40,
	0x4f, 0xae, 0x54, 0x1e, 0xa1, 0x47, 0x50, 0x0f, 0x11, 0x82, 0x0b, 0x97, 0x25, 0x5d, 0xa2, 0x88,
	0x38, 0x0e, 0xb1, 0x53, 0xd4, 0x17, 0xe0, 0xb9, 0x51, 0x36, 0x4e, 0xf9, 0x11, 0x12, 0x88, 0x8b,
	0xe5, 0x99, 0xf1, 0x8e, 0xc6, 0x63, 0xc3, 0x69, 0x51, 0x1a, 0x67, 0x96, 0x19, 0xe1, 0xd6, 0x36,
	0xab, 0x62, 0x46, 0x4c, 0x12, 0xa3, 0x74, 0x1a, 0x97, 0x46, 0x59, 0x2a, 0x77, 0x69, 0x4c, 0x8a,
	0xd5, 0xf9, 0x6b, 0x00, 0xe3, 0x0d, 0xbd, 0x5c, 0x13, 0x6e, 0x23, 0x7a, 0xae, 0xc8, 0x3a, 0x71,
	0x06, 0xc3, 0xc7, 0xb4, 0xb4, 0x6e, 0x83, 0x9a, 0x64, 0x67, 0xd6, 0x59, 0x0c, 0xa3, 0x77, 0x42,
	0x4c, 0x21, 0xcc, 0xd0, 0x8b, 0xff, 0x59, 0x3c, 0x60, 0x71, 0x02, 0x3d, 0xd2, 0x98, 0x66, 0x32,
	0x60, 0xa1, 0x01, 0x42, 0xc2, 0x20, 0x36, 0xb9, 0xc3, 0xd8, 0xc9, 0x2e, 0xf3, 0x2d, 0x14, 0x13,
	0xe8, 0x5b, 0x53, 0x95, 0x31, 0xc9, 0x1e, 0x0b, 0x1e, 0x89, 0x35, 0x74, 0x35, 0x39, 0x94, 0xfd,
	0x59, 0xb0, 0x18, 0xad, 0x96, 0xea, 0xfb, 0xec, 0xea, 0x73, 0x6e, 0x75, 0x45, 0xfb, 0x5b, 0xcc,
	0x2a, 0x8a, 0x78, 0x58, 0xdc, 0xc1, 0xd8, 0x91, 0x2e, 0x32, 0x74, 0xc4, 0xb4, 0x95, 0x83, 0xbf,
	0xd9, 0x7d, 0xb1, 0x11, 0x33, 0x18, 0xc5, 0xa8, 0x0b, 0x4c, 0x93, 0xfc, 0x06, 0x13, 0x19, 0x72,
	0xf4, 0x8f, 0xd4, 0x74, 0x05, 0x61, 0x3b, 0x2d, 0x8e, 0x21, 0x78, 0xa2, 0xbd, 0xef, 0xb1, 0xde,
	0xd6, 0x2d, 0xed, 0x6a, 0xc9, 0xd7, 0xd7, 0x80, 0xf9, 0x1a, 0x8e, 0x0e, 0x01, 0x6c, 0x61, 0x72,
	0x4b, 0x75, 0x71, 0x9a, 0xac, 0xc5, 0xa4, 0x7d, 0x86, 0x16, 0x72, 0x71, 0x0e, 0x5d, 0x65, 0xd9,
	0x23, 0x8c, 0x3c, 0x5a, 0x11, 0xf4, 0x6a, 0x07, 0x2b, 0xee, 0x61, 0xe0, 0xdd, 0xc4, 0xf9, 0xef,
	0xee, 0x3b, 0xbd, 0xf8, 0xf1, 0x5c, 0x13, 0x6b, 0xfe, 0xef, 0xa1, 0xcf, 0x7f, 0xea, 0xf2, 0x2d,
	0x00, 0x00, 0xff, 0xff, 0x16, 0x86, 0x10, 0xd4, 0x6e, 0x02, 0x00, 0x00,
}
